Version 1.0.3
Twispay/magento1.x pull request #4
Opened 2019-12-10 12:05 UTC by cosminbosutar

Improved the 'form' template.
Personalized the orders identifier to make it more framework specific.
Ensured that the "orderId" sent inside the request payment is always unique.
Updated the readme file.
Fixed the display of the administrator email address in case of payment failure.
Added check that excludes orders with the amount below or equal to zero.

2019-12-11 13:31 UTC, dragos-ursu requested changes
Please fix the few typos found.

2019-12-11 13:31 UTC, dragos-ursu commented on README.md
> +1. Login to the official Magento webssite and [login](https://account.magento.com/customer/account/login)
Please fix typo `webssite`.

2019-12-11 13:31 UTC, dragos-ursu commented on README.md
> +12. Paste the copied **Access Key** inside the **Paste extention key to install** and click on the **Install** button
Please fix typo `extention`.

2019-12-11 13:31 UTC, dragos-ursu commented on README.md
> +20. Enter your tehnical **Contact Email**. _(This will be displayed to customers in case of a payment error)_
Please fix typo `tehnical`.

2019-12-11 13:31 UTC, dragos-ursu commented on package.xml
>  Added daily sync with the Twispay server for recurring profiles.</notes>
Please fix wrong closing `</notes>`.

2019-12-11 13:31 UTC, dragos-ursu commented on app/locale/en_US/Twispay_Tpay.csv
>  " Removed redundant order witd ID: "," Removed redundant order witd ID: "
Please fix typo `witd`.

2019-12-11 13:31 UTC, dragos-ursu commented on app/locale/en_US/Twispay_Tpay.csv
>  " Payment for order #%s canceled as free trial perios are not allowed."," Payment for order #%s canceled as free trial perios are not allowed."
Please fix typo `perios`.

2019-12-11 15:02 UTC, cosminbosutar commented on README.md
> +1. Login to the official Magento webssite and [login](https://account.magento.com/customer/account/login)
Solved

2019-12-11 15:02 UTC, cosminbosutar commented on README.md
> +12. Paste the copied **Access Key** inside the **Paste extention key to install** and click on the **Install** button
Solved

2019-12-11 15:02 UTC, cosminbosutar commented on README.md
> +20. Enter your tehnical **Contact Email**. _(This will be displayed to customers in case of a payment error)_
Solved

2019-12-11 15:02 UTC, cosminbosutar commented on package.xml
>  Added daily sync with the Twispay server for recurring profiles.</notes>
Solved

2019-12-11 15:03 UTC, cosminbosutar commented on app/locale/en_US/Twispay_Tpay.csv
>  " Removed redundant order witd ID: "," Removed redundant order witd ID: "
Solved

2019-12-11 15:03 UTC, cosminbosutar commented on app/locale/en_US/Twispay_Tpay.csv
>  " Payment for order #%s canceled as free trial perios are not allowed."," Payment for order #%s canceled as free trial perios are not allowed."
Solved

2019-12-12 15:53 UTC, dragos-ursu commented
Code review done.

2019-12-12 15:54 UTC, dragos-ursu approved these changes
Code review done.

2020-01-07 16:03 UTC, merged